import type { Metadata } from "next";
import { Geist, Geist_Mono, Playfair_Display, Inter } from "next/font/google";
import { IoSettingsOutline } from "react-icons/io5";
import { BsJournal } from "react-icons/bs";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Yay!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${inter.variable} antialiased`}
      >
        <nav className="absolute top-0 left-0 right-0 flex flex-row justify-between w-4/5 m-auto text-center h-[6vh]">
          <div className="border-red-100 flex items-center">
            <Link href='/' className="font-header text-3xl text-center">ReQuillr</Link>
          </div>
          <div className="flex flex-row gap-9 items-center">
            <span className="text-2xl hover:cursor-pointer"><IoSettingsOutline /></span>
            <span className="text-2xl hover:cursor-pointer"><BsJournal /></span>
          </div>
        </nav>

        {children}

        <footer>
          <p className="absolute left-5 bottom-3 z-20">created by Coson Lu</p>
        </footer>
      </body>
    </html>
  );
}
